# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 7e41523
_src_path: gh:scipp/copier_template
description: A simple tool to create time-of-flight chopper cascade diagrams
max_python: '3.13'
min_python: '3.11'
namespace_package: ''
nightly_deps: scipp,plopp
orgname: scipp
prettyname: Tof
projectname: tof
related_projects: Scipp,Scippneutron,Plopp
year: 2025
