# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

name: Docs

on:
  workflow_dispatch:
    inputs:
      publish:
        default: false
        type: boolean
      version:
        default: ''
        required: false
        type: string
      branch:
        description: 'Branch/tag with documentation source. If not set, the current branch will be used.'
        default: ''
        required: false
        type: string
  workflow_call:
    inputs:
      publish:
        default: false
        type: boolean
      version:
        default: ''
        required: false
        type: string
      branch:
        description: 'Branch/tag with documentation source. If not set, the current branch will be used.'
        default: ''
        required: false
        type: string

env:
  VERSION: ${{ inputs.version }}

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt install --yes graphviz pandoc
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch == '' && github.ref_name || inputs.branch }}
          fetch-depth: 0  # history required so setuptools_scm can determine version
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/ci.txt
      - run: |
          python -m pip cache remove plopp
          tox --skip-pkg-install -e docs -- plopp==${VERSION}
          echo "target=$(python docs/version.py --version=${VERSION} --action=get-target)" >> $GITHUB_ENV
        if: ${{ inputs.publish }}
      - run: tox -e docs
        if: ${{ !inputs.publish }}
      - uses: actions/upload-artifact@v3
        with:
          name: html
          path: html/

      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: ${{ inputs.publish }}
        with:
          branch: gh-pages
          folder: html
          target-folder: ${{ env.target }}
          single-commit: true
          clean-exclude: release
